#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("iVoting.Droid.Resource", IsApplication=true)]

namespace iVoting.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::iVoting.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::iVoting.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::iVoting.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::iVoting.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::iVoting.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::iVoting.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::iVoting.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::iVoting.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::iVoting.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::iVoting.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::iVoting.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::iVoting.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::iVoting.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::iVoting.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::iVoting.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::iVoting.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::iVoting.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::iVoting.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::iVoting.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::iVoting.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::iVoting.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::iVoting.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::iVoting.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::iVoting.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::iVoting.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::iVoting.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010020
			public const int ahBarColor = 2130772000;
			
			// aapt resource value: 0x7f010028
			public const int ahBarLength = 2130772008;
			
			// aapt resource value: 0x7f010027
			public const int ahBarWidth = 2130772007;
			
			// aapt resource value: 0x7f010025
			public const int ahCircleColor = 2130772005;
			
			// aapt resource value: 0x7f010024
			public const int ahDelayMillis = 2130772004;
			
			// aapt resource value: 0x7f010026
			public const int ahRadius = 2130772006;
			
			// aapt resource value: 0x7f010021
			public const int ahRimColor = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int ahRimWidth = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int ahSpinSpeed = 2130772003;
			
			// aapt resource value: 0x7f01001d
			public const int ahText = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int ahTextColor = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int ahTextSize = 2130771999;
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int cardBackgroundColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardCornerRadius = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int cardElevation = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int cardMaxElevation = 2130771977;
			
			// aapt resource value: 0x7f01000b
			public const int cardPreventCornerOverlap = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int cardUseCompatPadding = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010015
			public const int com_facebook_auxiliary_view_position = 2130771989;
			
			// aapt resource value: 0x7f010017
			public const int com_facebook_confirm_logout = 2130771991;
			
			// aapt resource value: 0x7f010011
			public const int com_facebook_foreground_color = 2130771985;
			
			// aapt resource value: 0x7f010016
			public const int com_facebook_horizontal_alignment = 2130771990;
			
			// aapt resource value: 0x7f01001c
			public const int com_facebook_is_cropped = 2130771996;
			
			// aapt resource value: 0x7f010018
			public const int com_facebook_login_text = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int com_facebook_logout_text = 2130771993;
			
			// aapt resource value: 0x7f010012
			public const int com_facebook_object_id = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int com_facebook_object_type = 2130771987;
			
			// aapt resource value: 0x7f01001b
			public const int com_facebook_preset_size = 2130771995;
			
			// aapt resource value: 0x7f010014
			public const int com_facebook_style = 2130771988;
			
			// aapt resource value: 0x7f01001a
			public const int com_facebook_tooltip_mode = 2130771994;
			
			// aapt resource value: 0x7f01000c
			public const int contentPadding = 2130771980;
			
			// aapt resource value: 0x7f010010
			public const int contentPaddingBottom = 2130771984;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingLeft = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingRight = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int contentPaddingTop = 2130771983;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050029
			public const int accent = 2131034153;
			
			// aapt resource value: 0x7f050011
			public const int cardview_dark_background = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int cardview_light_background = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int cardview_shadow_end_color = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int cardview_shadow_start_color = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int com_facebook_blue = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int com_facebook_button_background_color = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int com_facebook_button_background_color_disabled = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int com_facebook_button_background_color_focused = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int com_facebook_button_background_color_focused_disabled = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int com_facebook_button_background_color_pressed = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int com_facebook_button_background_color_selected = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int com_facebook_button_border_color_focused = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int com_facebook_button_login_silver_background_color = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int com_facebook_button_login_silver_background_color_pressed = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int com_facebook_button_send_background_color = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int com_facebook_button_send_background_color_pressed = 2131034144;
			
			// aapt resource value: 0x7f05002c
			public const int com_facebook_button_text_color = 2131034156;
			
			// aapt resource value: 0x7f050021
			public const int com_facebook_device_auth_text = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int com_facebook_likeboxcountview_border_color = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int com_facebook_likeboxcountview_text_color = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int com_facebook_likeview_text_color = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int com_facebook_messenger_blue = 2131034149;
			
			// aapt resource value: 0x7f05002d
			public const int com_facebook_send_button_text_color = 2131034157;
			
			// aapt resource value: 0x7f050026
			public const int com_facebook_share_button_text_color = 2131034150;
			
			// aapt resource value: 0x7f050008
			public const int common_action_bar_splitter = 2131034120;
			
			// aapt resource value: 0x7f05002e
			public const int common_google_signin_btn_text_dark = 2131034158;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_dark_default = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_signin_btn_text_dark_disabled = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_signin_btn_text_dark_focused = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_signin_btn_text_dark_pressed = 2131034122;
			
			// aapt resource value: 0x7f05002f
			public const int common_google_signin_btn_text_light = 2131034159;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_signin_btn_text_light_default = 2131034125;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_signin_btn_text_light_disabled = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_signin_btn_text_light_pressed = 2131034126;
			
			// aapt resource value: 0x7f050030
			public const int common_plus_signin_btn_text_dark = 2131034160;
			
			// aapt resource value: 0x7f050000
			public const int common_plus_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_plus_signin_btn_text_dark_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_plus_signin_btn_text_dark_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_plus_signin_btn_text_dark_pressed = 2131034113;
			
			// aapt resource value: 0x7f050031
			public const int common_plus_signin_btn_text_light = 2131034161;
			
			// aapt resource value: 0x7f050004
			public const int common_plus_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_plus_signin_btn_text_light_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_plus_signin_btn_text_light_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_plus_signin_btn_text_light_pressed = 2131034117;
			
			// aapt resource value: 0x7f050027
			public const int primary = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int primaryDark = 2131034152;
			
			// aapt resource value: 0x7f05002b
			public const int splash_background = 2131034155;
			
			// aapt resource value: 0x7f05002a
			public const int window_background = 2131034154;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int cardview_compat_inset_shadow = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int cardview_default_elevation = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int cardview_default_radius = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int com_facebook_auth_dialog_corner_radius = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int com_facebook_auth_dialog_corner_radius_oversized = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int com_facebook_button_corner_radius = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int com_facebook_likeboxcountview_border_radius = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int com_facebook_likeboxcountview_border_width = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int com_facebook_likeboxcountview_caret_height = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int com_facebook_likeboxcountview_caret_width = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int com_facebook_likeboxcountview_text_padding = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int com_facebook_likeboxcountview_text_size = 2131296267;
			
			// aapt resource value: 0x7f09000c
			public const int com_facebook_likeview_edge_padding = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int com_facebook_likeview_internal_padding = 2131296269;
			
			// aapt resource value: 0x7f09000e
			public const int com_facebook_likeview_text_size = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int com_facebook_profilepictureview_preset_size_large = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int com_facebook_profilepictureview_preset_size_normal = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int com_facebook_profilepictureview_preset_size_small = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int com_facebook_share_button_compound_drawable_padding = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int com_facebook_share_button_padding_bottom = 2131296275;
			
			// aapt resource value: 0x7f090014
			public const int com_facebook_share_button_padding_left = 2131296276;
			
			// aapt resource value: 0x7f090015
			public const int com_facebook_share_button_padding_right = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int com_facebook_share_button_padding_top = 2131296278;
			
			// aapt resource value: 0x7f090017
			public const int com_facebook_share_button_text_size = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int com_facebook_tooltip_horizontal_padding = 2131296280;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int com_facebook_auth_dialog_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int com_facebook_auth_dialog_cancel_background = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int com_facebook_auth_dialog_header_background = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int com_facebook_button_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int com_facebook_button_icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int com_facebook_button_icon_blue = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int com_facebook_button_icon_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int com_facebook_button_like_background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int com_facebook_button_like_icon_selected = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int com_facebook_button_login_silver_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int com_facebook_button_send_background = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int com_facebook_button_send_icon_blue = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int com_facebook_button_send_icon_white = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int com_facebook_close = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int com_facebook_favicon_white = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int com_facebook_profile_picture_blank_portrait = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_profile_picture_blank_square = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_send_button_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_tooltip_black_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_tooltip_black_bottomnub = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_tooltip_black_topnub = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_tooltip_black_xout = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_tooltip_blue_background = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_tooltip_blue_bottomnub = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_tooltip_blue_topnub = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_tooltip_blue_xout = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_full_open_on_phone = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_icon_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_icon_dark_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_icon_dark_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_icon_dark_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_icon_dark_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_icon_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_google_signin_btn_icon_light_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_google_signin_btn_icon_light_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_google_signin_btn_icon_light_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_google_signin_btn_icon_light_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_google_signin_btn_text_dark = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_google_signin_btn_text_dark_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_google_signin_btn_text_dark_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_google_signin_btn_text_dark_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_google_signin_btn_text_dark_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_google_signin_btn_text_light = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_google_signin_btn_text_light_disabled = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_google_signin_btn_text_light_focused = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_google_signin_btn_text_light_normal = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_google_signin_btn_text_light_pressed = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_ic_googleplayservices = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_icon_dark = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int common_plus_signin_btn_icon_dark_focused = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int common_plus_signin_btn_icon_dark_normal = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int common_plus_signin_btn_icon_light = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int common_plus_signin_btn_icon_light_disabled = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int common_plus_signin_btn_icon_light_focused = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int common_plus_signin_btn_icon_light_normal = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int common_plus_signin_btn_icon_light_pressed = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int common_plus_signin_btn_text_dark = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int common_plus_signin_btn_text_dark_disabled = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int common_plus_signin_btn_text_dark_focused = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int common_plus_signin_btn_text_dark_normal = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int common_plus_signin_btn_text_dark_pressed = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int common_plus_signin_btn_text_light = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int common_plus_signin_btn_text_light_disabled = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int common_plus_signin_btn_text_light_focused = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int common_plus_signin_btn_text_light_normal = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int common_plus_signin_btn_text_light_pressed = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_errorstatus = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_plusone_medium_off_client = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_plusone_small_off_client = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_plusone_standard_off_client = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_plusone_tall_off_client = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_successstatus = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int messenger_bubble_large_blue = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int messenger_bubble_large_white = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int messenger_bubble_small_blue = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int messenger_bubble_small_white = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int messenger_button_blue_bg_round = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int messenger_button_blue_bg_selector = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int messenger_button_send_round_shadow = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int messenger_button_white_bg_round = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int messenger_button_white_bg_selector = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int roundedbg = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int roundedbgdark = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int sample = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int splash_logo = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int splash_screen = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int votebg = 2130837592;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_height = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int adjust_width = 2131361799;
			
			// aapt resource value: 0x7f0a0003
			public const int auto = 2131361795;
			
			// aapt resource value: 0x7f0a0014
			public const int automatic = 2131361812;
			
			// aapt resource value: 0x7f0a000e
			public const int bottom = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int box_count = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int button = 2131361805;
			
			// aapt resource value: 0x7f0a001f
			public const int cancel_button = 2131361823;
			
			// aapt resource value: 0x7f0a0011
			public const int center = 2131361809;
			
			// aapt resource value: 0x7f0a0021
			public const int com_facebook_body_frame = 2131361825;
			
			// aapt resource value: 0x7f0a0023
			public const int com_facebook_button_xout = 2131361827;
			
			// aapt resource value: 0x7f0a001c
			public const int com_facebook_device_auth_instructions = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int com_facebook_device_dialog_title = 2131361819;
			
			// aapt resource value: 0x7f0a001a
			public const int com_facebook_fragment_container = 2131361818;
			
			// aapt resource value: 0x7f0a0020
			public const int com_facebook_login_activity_progress_bar = 2131361824;
			
			// aapt resource value: 0x7f0a0025
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361829;
			
			// aapt resource value: 0x7f0a0024
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361828;
			
			// aapt resource value: 0x7f0a0022
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361826;
			
			// aapt resource value: 0x7f0a001d
			public const int confirmation_code = 2131361821;
			
			// aapt resource value: 0x7f0a0004
			public const int dark = 2131361796;
			
			// aapt resource value: 0x7f0a0015
			public const int display_always = 2131361813;
			
			// aapt resource value: 0x7f0a0028
			public const int employeeloginview_btnLogin = 2131361832;
			
			// aapt resource value: 0x7f0a0026
			public const int employeeloginview_txtAccount = 2131361830;
			
			// aapt resource value: 0x7f0a0027
			public const int employeeloginview_txtPassword = 2131361831;
			
			// aapt resource value: 0x7f0a002a
			public const int facebookloginview_loginbutton = 2131361834;
			
			// aapt resource value: 0x7f0a0029
			public const int facebookloginview_profilePicture = 2131361833;
			
			// aapt resource value: 0x7f0a0030
			public const int googleloginview_btnDisconnect = 2131361840;
			
			// aapt resource value: 0x7f0a002d
			public const int googleloginview_btnSignIn = 2131361837;
			
			// aapt resource value: 0x7f0a002f
			public const int googleloginview_btnSignOut = 2131361839;
			
			// aapt resource value: 0x7f0a002c
			public const int googleloginview_status = 2131361836;
			
			// aapt resource value: 0x7f0a002b
			public const int googleloginview_title = 2131361835;
			
			// aapt resource value: 0x7f0a0000
			public const int icon_only = 2131361792;
			
			// aapt resource value: 0x7f0a000f
			public const int inline = 2131361807;
			
			// aapt resource value: 0x7f0a0017
			public const int large = 2131361815;
			
			// aapt resource value: 0x7f0a0012
			public const int left = 2131361810;
			
			// aapt resource value: 0x7f0a0005
			public const int light = 2131361797;
			
			// aapt resource value: 0x7f0a0033
			public const int loadingImage = 2131361843;
			
			// aapt resource value: 0x7f0a0031
			public const int loadingProgressBar = 2131361841;
			
			// aapt resource value: 0x7f0a0034
			public const int loadingProgressWheel = 2131361844;
			
			// aapt resource value: 0x7f0a0037
			public const int loginselectionview_btnEmployee = 2131361847;
			
			// aapt resource value: 0x7f0a0036
			public const int loginselectionview_btnFacebook = 2131361846;
			
			// aapt resource value: 0x7f0a0035
			public const int loginselectionview_btnGoogle = 2131361845;
			
			// aapt resource value: 0x7f0a0038
			public const int menu_listview = 2131361848;
			
			// aapt resource value: 0x7f0a003c
			public const int menuview_voteitemview_btnVote = 2131361852;
			
			// aapt resource value: 0x7f0a0039
			public const int menuview_voteitemview_layoutBackground = 2131361849;
			
			// aapt resource value: 0x7f0a003b
			public const int menuview_voteitemview_lbDescription = 2131361851;
			
			// aapt resource value: 0x7f0a003a
			public const int menuview_voteitemview_lbTitle = 2131361850;
			
			// aapt resource value: 0x7f0a003d
			public const int messenger_send_button = 2131361853;
			
			// aapt resource value: 0x7f0a0016
			public const int never_display = 2131361814;
			
			// aapt resource value: 0x7f0a0008
			public const int none = 2131361800;
			
			// aapt resource value: 0x7f0a0018
			public const int normal = 2131361816;
			
			// aapt resource value: 0x7f0a0009
			public const int open_graph = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int page = 2131361802;
			
			// aapt resource value: 0x7f0a001e
			public const int progress_bar = 2131361822;
			
			// aapt resource value: 0x7f0a0013
			public const int right = 2131361811;
			
			// aapt resource value: 0x7f0a002e
			public const int sign_out_and_disconnect = 2131361838;
			
			// aapt resource value: 0x7f0a0019
			public const int small = 2131361817;
			
			// aapt resource value: 0x7f0a0001
			public const int standard = 2131361793;
			
			// aapt resource value: 0x7f0a0032
			public const int textViewStatus = 2131361842;
			
			// aapt resource value: 0x7f0a0010
			public const int top = 2131361808;
			
			// aapt resource value: 0x7f0a000b
			public const int unknown = 2131361803;
			
			// aapt resource value: 0x7f0a003e
			public const int votedescview_btnConfirm = 2131361854;
			
			// aapt resource value: 0x7f0a0040
			public const int votedescview_contentview_btnConfirm = 2131361856;
			
			// aapt resource value: 0x7f0a003f
			public const int votedescview_fragmentcontent = 2131361855;
			
			// aapt resource value: 0x7f0a0042
			public const int votedescview_type01_descimage = 2131361858;
			
			// aapt resource value: 0x7f0a0041
			public const int votedescview_type01_lbDesc = 2131361857;
			
			// aapt resource value: 0x7f0a0043
			public const int votedescview_type02_lbDesc = 2131361859;
			
			// aapt resource value: 0x7f0a0044
			public const int votedescview_type02_player = 2131361860;
			
			// aapt resource value: 0x7f0a0046
			public const int votenow_content = 2131361862;
			
			// aapt resource value: 0x7f0a0045
			public const int votenowview_btnConfirm = 2131361861;
			
			// aapt resource value: 0x7f0a0048
			public const int votetitleview_btnCancel = 2131361864;
			
			// aapt resource value: 0x7f0a0049
			public const int votetitleview_btnConfirm = 2131361865;
			
			// aapt resource value: 0x7f0a0047
			public const int votetitleview_txtVoteTitle = 2131361863;
			
			// aapt resource value: 0x7f0a0002
			public const int wide = 2131361794;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int com_facebook_activity_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int com_facebook_device_auth_dialog_fragment = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int com_facebook_login_fragment = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int com_facebook_tooltip_bubble = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int employeeloginview = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int facebookloginview = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int googleloginview = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int loading = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int loadingimage = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int loadingprogress = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int loginselectionview = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int menuview = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int menuview_voteitemview = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int messenger_button_send_blue_large = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int messenger_button_send_blue_round = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int messenger_button_send_blue_small = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int messenger_button_send_white_large = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int messenger_button_send_white_round = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int messenger_button_send_white_small = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int votedescriptionview = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int votedescview_content = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int votedescview_type01 = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int votedescview_type02 = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int votenowview = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int voteresultview = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int votetitleview = 2130968601;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060032
			public const int app_id = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int app_name = 2131099699;
			
			// aapt resource value: 0x7f06001d
			public const int auth_google_play_services_client_facebook_display_name = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int auth_google_play_services_client_google_display_name = 2131099676;
			
			// aapt resource value: 0x7f06001f
			public const int com_facebook_device_auth_instructions = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int com_facebook_image_download_unknown_error = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int com_facebook_internet_permission_error_message = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int com_facebook_internet_permission_error_title = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int com_facebook_like_button_liked = 2131099683;
			
			// aapt resource value: 0x7f060024
			public const int com_facebook_like_button_not_liked = 2131099684;
			
			// aapt resource value: 0x7f060025
			public const int com_facebook_loading = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int com_facebook_loginview_cancel_action = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int com_facebook_loginview_log_in_button = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int com_facebook_loginview_log_in_button_long = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int com_facebook_loginview_log_out_action = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int com_facebook_loginview_log_out_button = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int com_facebook_loginview_logged_in_as = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int com_facebook_loginview_logged_in_using_facebook = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int com_facebook_send_button_text = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int com_facebook_share_button_text = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int com_facebook_tooltip_default = 2131099695;
			
			// aapt resource value: 0x7f060015
			public const int common_google_play_services_api_unavailable_text = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int common_google_play_services_enable_button = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int common_google_play_services_enable_text = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int common_google_play_services_enable_title = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int common_google_play_services_install_button = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_install_text_phone = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_play_services_install_text_tablet = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_google_play_services_install_title = 2131099649;
			
			// aapt resource value: 0x7f060010
			public const int common_google_play_services_invalid_account_text = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_play_services_invalid_account_title = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_play_services_network_error_text = 2131099662;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_play_services_network_error_title = 2131099661;
			
			// aapt resource value: 0x7f060000
			public const int common_google_play_services_notification_ticker = 2131099648;
			
			// aapt resource value: 0x7f060019
			public const int common_google_play_services_restricted_profile_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int common_google_play_services_restricted_profile_title = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int common_google_play_services_sign_in_failed_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int common_google_play_services_sign_in_failed_title = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int common_google_play_services_unknown_issue = 2131099678;
			
			// aapt resource value: 0x7f060012
			public const int common_google_play_services_unsupported_text = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int common_google_play_services_unsupported_title = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int common_google_play_services_update_button = 2131099667;
			
			// aapt resource value: 0x7f060009
			public const int common_google_play_services_update_text = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int common_google_play_services_update_title = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_play_services_updating_text = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_play_services_updating_title = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_play_services_wear_update_text = 2131099658;
			
			// aapt resource value: 0x7f060014
			public const int common_open_on_phone = 2131099668;
			
			// aapt resource value: 0x7f06001a
			public const int common_signin_button_text = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int common_signin_button_text_long = 2131099675;
			
			// aapt resource value: 0x7f060034
			public const int employee = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int facebook = 2131099701;
			
			// aapt resource value: 0x7f060037
			public const int facebook_app_id = 2131099703;
			
			// aapt resource value: 0x7f060036
			public const int google = 2131099702;
			
			// aapt resource value: 0x7f060031
			public const int library_name = 2131099697;
			
			// aapt resource value: 0x7f060030
			public const int messenger_send_button_text = 2131099696;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int Base_CardView = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int CardView = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int CardView_Dark = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int CardView_Light = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MessengerButton = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MessengerButton_Blue = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MessengerButton_Blue_Large = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MessengerButton_Blue_Small = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MessengerButton_White = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int MessengerButton_White_Large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MessengerButton_White_Small = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int MessengerButtonText = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int MessengerButtonText_Blue = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MessengerButtonText_Blue_Large = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MessengerButtonText_Blue_Small = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int MessengerButtonText_White = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int MessengerButtonText_White_Large = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int MessengerButtonText_White_Small = 2131230737;
			
			// aapt resource value: 0x7f08001b
			public const int MyTheme = 2131230747;
			
			// aapt resource value: 0x7f08001a
			public const int MyTheme_Base = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int MyTheme_Splash = 2131230748;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_auth_dialog = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_button = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int com_facebook_button_like = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int com_facebook_button_send = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int com_facebook_button_share = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int com_facebook_loginview_default_style = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int com_facebook_loginview_silver_style = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int tooltip_bubble_text = 2131230745;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					16843071,
					16843072,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] com_facebook_like_view = new int[]
			{
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[]
			{
					2130771991,
					2130771992,
					2130771993,
					2130771994};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[]
			{
					2130771995,
					2130771996};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
